[phases.setup]
# SQLiteパッケージを削除 - MySQLのみ使用

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "echo 'DB_HOST='$DB_HOST && echo 'DB_PORT='$DB_PORT && echo 'DB_DATABASE='$DB_DATABASE && echo 'DB_USERNAME='$DB_USERNAME && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"