[build]
builder = "nixpacks"

[deploy]
startCommand = "bash deploy.sh"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
SESSION_DRIVER = "database"
CACHE_STORE = "database"
QUEUE_CONNECTION = "database"