<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 各都道府県から代表的なイベントを3件ずつ選出（141件）
        $events = [
            // 北海道 (3件)
            [
                'title' => 'さっぽろ雪まつり',
                'description' => '世界的に有名な雪と氷の祭典。大小様々な雪像や氷像が展示され、ライトアップも行われます。',
                'overview' => '大小様々な雪像・氷像が並ぶ冬の祭典。幻想的なライトアップやイベントも楽しめます。',
                'prefecture' => '北海道',
                'location' => '大通公園',
                'start_date' => '2026-02-01',
                'end_date' => '2026-02-12',
                'category' => 'その他',
                'tags' => '["雪まつり","冬","祭り","氷像"]',
                'access' => '札幌市営地下鉄大通駅、すすきの駅、さっぽろ駅直結',
                'url' => '',
                'organizer' => '',
                'display_order' => 0,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '函館クリスマスファンタジー',
                'description' => 'ベイエリアに巨大なクリスマスツリーが登場し、幻想的なイルミネーションが街を彩ります。',
                'overview' => 'ベイエリアに巨大ツリーが登場。毎夜花火も上がり、ロマンチックな夜を演出します。',
                'prefecture' => '北海道',
                'location' => '函館ベイエリア',
                'start_date' => '2025-12-01',
                'end_date' => '2025-12-25',
                'category' => 'その他',
                'tags' => '["クリスマス","イルミネーション","冬","フェスティバル"]',
                'access' => '函館市電十字街停留場から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'おたる雪あかりの路',
                'description' => '小樽の街並みをろうそくの灯りが優しく包み込む、幻想的な冬のイベントです。',
                'overview' => '小樽運河沿いに無数のろうそくが灯され、幻想的な雰囲気に包まれます。',
                'prefecture' => '北海道',
                'location' => '小樽運河周辺',
                'start_date' => '2026-02-08',
                'end_date' => '2026-02-16',
                'category' => 'その他',
                'tags' => '["冬","ろうそく","祭り","幻想的"]',
                'access' => 'JR小樽駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 青森県 (3件)
            [
                'title' => '青森ねぶた祭',
                'description' => '青森の夏を代表する豪華絢爛な祭り。巨大な武者絵の灯籠が夜の街を練り歩きます。',
                'overview' => '勇壮な武者絵の巨大灯籠と太鼓、笛の音が響く青森の夏祭り。',
                'prefecture' => '青森県',
                'location' => '青森市中心街',
                'start_date' => '2025-08-02',
                'end_date' => '2025-08-07',
                'category' => '祭り',
                'tags' => '["ねぶた","夏祭り","伝統","灯籠"]',
                'access' => 'JR青森駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '弘前さくらまつり',
                'description' => '日本三大桜の名所として知られる弘前公園で開催される桜祭り。約2,600本の桜が咲き誇ります。',
                'overview' => '弘前城を背景に約2,600本の桜が彩る日本有数の桜まつり。',
                'prefecture' => '青森県',
                'location' => '弘前公園',
                'start_date' => '2025-04-23',
                'end_date' => '2025-05-05',
                'category' => '自然',
                'tags' => '["桜","春","弘前城","花見"]',
                'access' => 'JR弘前駅からバス約15分',
                'url' => '',
                'organizer' => '',
                'display_order' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '十和田湖冬物語',
                'description' => '雪と氷に包まれた十和田湖畔で開催される冬のイベント。花火や雪像、かまくらが楽しめます。',
                'overview' => '雪景色の十和田湖畔で花火やかまくら、アイスバーなどが楽しめる冬祭り。',
                'prefecture' => '青森県',
                'location' => '十和田湖畔休屋',
                'start_date' => '2026-02-01',
                'end_date' => '2026-02-28',
                'category' => 'その他',
                'tags' => '["冬","花火","かまくら","十和田湖"]',
                'access' => 'JR八戸駅からバス約2時間',
                'url' => '',
                'organizer' => '',
                'display_order' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 岩手県 (3件)
            [
                'title' => '盛岡さんさ踊り',
                'description' => '岩手県を代表する伝統芸能。太鼓と踊りが織りなす勇壮で美しい祭りです。',
                'overview' => '太鼓の音と華麗な踊りが盛岡の夏を彩る、岩手県最大の祭り。',
                'prefecture' => '岩手県',
                'location' => '盛岡市中央通',
                'start_date' => '2025-08-01',
                'end_date' => '2025-08-04',
                'category' => '祭り',
                'tags' => '["さんさ踊り","太鼓","夏祭り","伝統芸能"]',
                'access' => 'JR盛岡駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '花巻まつり',
                'description' => '宮沢賢治の故郷で開催される祭り。風流山車と神輿のパレードが見どころです。',
                'overview' => '400年以上の歴史を持つ花巻の秋祭り。華麗な風流山車が街を練り歩きます。',
                'prefecture' => '岩手県',
                'location' => '花巻市街地',
                'start_date' => '2025-09-12',
                'end_date' => '2025-09-14',
                'category' => '祭り',
                'tags' => '["山車","秋祭り","伝統","花巻"]',
                'access' => 'JR花巻駅から徒歩約15分',
                'url' => '',
                'organizer' => '',
                'display_order' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '中尊寺紅葉ライトアップ',
                'description' => '世界遺産中尊寺の美しい紅葉を夜間ライトアップ。幻想的な光景が楽しめます。',
                'overview' => '平泉の世界遺産中尊寺で行われる秋の夜間ライトアップイベント。',
                'prefecture' => '岩手県',
                'location' => '中尊寺',
                'start_date' => '2025-10-20',
                'end_date' => '2025-11-10',
                'category' => '自然',
                'tags' => '["紅葉","ライトアップ","世界遺産","中尊寺"]',
                'access' => 'JR平泉駅からバス約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 宮城県 (3件)
            [
                'title' => '仙台七夕まつり',
                'description' => '日本三大七夕祭りの一つ。商店街に色とりどりの豪華な七夕飾りが並びます。',
                'overview' => '伊達政宗公の時代から続く伝統的な七夕祭り。華麗な飾りが仙台の街を彩ります。',
                'prefecture' => '宮城県',
                'location' => '仙台市中心部商店街',
                'start_date' => '2025-08-06',
                'end_date' => '2025-08-08',
                'category' => '祭り',
                'tags' => '["七夕","夏祭り","伝統","商店街"]',
                'access' => 'JR仙台駅から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '松島紅葉ライトアップ',
                'description' => '日本三景の一つ松島で開催される紅葉のライトアップ。円通院を中心とした幻想的な景観が楽しめます。',
                'overview' => '日本三景松島の寺院群で行われる秋の夜間ライトアップ。',
                'prefecture' => '宮城県',
                'location' => '松島町（円通院など）',
                'start_date' => '2025-10-26',
                'end_date' => '2025-11-17',
                'category' => '自然',
                'tags' => '["紅葉","ライトアップ","松島","日本三景"]',
                'access' => 'JR松島海岸駅から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '白石城桜まつり',
                'description' => '白石城跡の桜が満開になる時期に開催される桜祭り。城跡と桜のコラボレーションが美しいです。',
                'overview' => '復元された白石城と約200本の桜が織りなす春の祭典。',
                'prefecture' => '宮城県',
                'location' => '白石城跡',
                'start_date' => '2025-04-10',
                'end_date' => '2025-05-05',
                'category' => '自然',
                'tags' => '["桜","城","春","白石"]',
                'access' => 'JR白石駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 秋田県 (3件)
            [
                'title' => '秋田竿燈まつり',
                'description' => '東北三大祭りの一つ。竹竿に提灯を吊るした竿燈を手のひらや額で支える妙技が見どころです。',
                'overview' => '280年以上の歴史を持つ伝統的な祭り。竿燈の妙技と美しい提灯の灯りが夜を彩ります。',
                'prefecture' => '秋田県',
                'location' => '秋田市竿燈大通り',
                'start_date' => '2025-08-03',
                'end_date' => '2025-08-06',
                'category' => '祭り',
                'tags' => '["竿燈","夏祭り","東北三大祭り","妙技"]',
                'access' => 'JR秋田駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '横手かまくらまつり',
                'description' => '約450年の歴史を持つ雪国の伝統行事。美しいかまくらが街を彩り、子どもたちが甘酒をふるまいます。',
                'overview' => '雪国横手の冬を代表するかまくら祭り。約100基のかまくらが幻想的な雪景色を演出。',
                'prefecture' => '秋田県',
                'location' => '横手市内各所',
                'start_date' => '2026-02-15',
                'end_date' => '2026-02-16',
                'category' => 'その他',
                'tags' => '["かまくら","冬","雪","伝統行事"]',
                'access' => 'JR横手駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 13,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '男鹿のナマハゲ',
                'description' => 'ユネスコ無形文化遺産に登録された男鹿半島の伝統行事。鬼のような面をつけたナマハゲが各家を回ります。',
                'overview' => '大晦日の夜に行われる男鹿半島の伝統行事。ナマハゲが家々を回り厄払いをします。',
                'prefecture' => '秋田県',
                'location' => '男鹿半島各地',
                'start_date' => '2025-12-31',
                'end_date' => '2025-12-31',
                'category' => '祭り',
                'tags' => '["ナマハゲ","伝統行事","ユネスコ","大晦日"]',
                'access' => 'JR男鹿駅からバス約30分',
                'url' => '',
                'organizer' => '',
                'display_order' => 14,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 山形県 (3件)
            [
                'title' => '山形花笠まつり',
                'description' => '東北四大祭りの一つ。「花笠音頭」に合わせて踊り手が街を練り歩く華やかな祭りです。',
                'overview' => '「ヤッショ、マカショ」の掛け声と花笠踊りが響く山形の夏祭り。',
                'prefecture' => '山形県',
                'location' => '山形市十日町・本町・七日町通り',
                'start_date' => '2025-08-05',
                'end_date' => '2025-08-07',
                'category' => '祭り',
                'tags' => '["花笠踊り","夏祭り","音頭","東北四大祭り"]',
                'access' => 'JR山形駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '蔵王樹氷まつり',
                'description' => '蔵王の樹氷（アイスモンスター）を楽しむ冬のイベント。ライトアップされた樹氷は幻想的です。',
                'overview' => '世界的に有名な蔵王の樹氷を間近で観賞できる冬限定のイベント。',
                'prefecture' => '山形県',
                'location' => '蔵王温泉スキー場',
                'start_date' => '2025-12-28',
                'end_date' => '2026-02-28',
                'category' => '自然',
                'tags' => '["樹氷","冬","ライトアップ","蔵王"]',
                'access' => 'JR山形駅からバス約40分',
                'url' => '',
                'organizer' => '',
                'display_order' => 16,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '上山城まつり',
                'description' => '桜の季節に開催される上山城のまつり。城と桜のコラボレーションが美しい春のイベントです。',
                'overview' => '月岡公園の桜と復元された上山城が織りなす春の祭典。',
                'prefecture' => '山形県',
                'location' => '上山城・月岡公園',
                'start_date' => '2025-04-20',
                'end_date' => '2025-05-05',
                'category' => '自然',
                'tags' => '["桜","城","春","上山"]',
                'access' => 'JR上山温泉駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 17,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 福島県 (3件)
            [
                'title' => '相馬野馬追',
                'description' => '1000年以上の歴史を持つ世界最大規模の馬事芸能。甲冑を身にまとった騎馬武者が駆け巡ります。',
                'overview' => '戦国時代さながらの甲冑競馬と神旗争奪戦が見どころの勇壮な祭り。',
                'prefecture' => '福島県',
                'location' => '南相馬市原町区雲雀ヶ原祭場地',
                'start_date' => '2025-07-26',
                'end_date' => '2025-07-28',
                'category' => '祭り',
                'tags' => '["野馬追","騎馬","甲冑","伝統"]',
                'access' => 'JR原ノ町駅から徒歩約20分',
                'url' => '',
                'organizer' => '',
                'display_order' => 18,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '福島わらじまつり',
                'description' => '長さ12mの大わらじを担いで練り歩く福島の夏祭り。わらじ音頭に合わせた踊りも見どころです。',
                'overview' => '巨大なわらじを担ぐ勇壮な祭りと市民参加のわらじ踊りが楽しめる夏のイベント。',
                'prefecture' => '福島県',
                'location' => '福島市国道13号・信夫通り',
                'start_date' => '2025-08-02',
                'end_date' => '2025-08-03',
                'category' => '祭り',
                'tags' => '["わらじ","夏祭り","踊り","福島"]',
                'access' => 'JR福島駅から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 19,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '鶴ヶ城さくらまつり',
                'description' => '会津若松のシンボル鶴ヶ城の桜まつり。約1000本の桜が赤瓦の天守閣を彩ります。',
                'overview' => '白亜の城と赤瓦、桜のコントラストが美しい会津の春の名物イベント。',
                'prefecture' => '福島県',
                'location' => '鶴ヶ城公園',
                'start_date' => '2025-04-15',
                'end_date' => '2025-05-15',
                'category' => '自然',
                'tags' => '["桜","城","会津","鶴ヶ城"]',
                'access' => 'JR会津若松駅からバス約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 20,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 茨城県 (3件)
            [
                'title' => 'ひたちなか海浜公園コキアまつり',
                'description' => '国営ひたちなか海浜公園のコキアが満開になる時期の名物イベント。青いコキアの絨毯が広がります。',
                'overview' => '約530万本のコキアが青い絨毯のように広がる春の絶景。',
                'prefecture' => '茨城県',
                'location' => '国営ひたちなか海浜公園',
                'start_date' => '2025-04-25',
                'end_date' => '2025-05-15',
                'category' => '自然',
                'tags' => '["コキア","花","春","ひたちなか"]',
                'access' => 'JR勝田駅からバス約40分',
                'url' => '',
                'organizer' => '',
                'display_order' => 21,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '古河花火大会',
                'description' => '関東最大級の打上花火数を誇る花火大会。渡良瀬川で約2万発の花火が打ち上げられます。',
                'overview' => '約100万人の観客が訪れる関東最大級の花火大会。',
                'prefecture' => '茨城県',
                'location' => '渡良瀬川畑倉大橋下流',
                'start_date' => '2025-08-02',
                'end_date' => '2025-08-02',
                'category' => '祭り',
                'tags' => '["花火","夏","古河","大会"]',
                'access' => 'JR古河駅から徒歩約50分',
                'url' => '',
                'organizer' => '',
                'display_order' => 22,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '袋田花大遣い',
                'description' => '茶事ではない方法で花を楽しむイベント。撮影スポットとしても人気で、関東方面から多くの観光客が訪れます。',
                'overview' => '1,000万本の花で彩られた袋田の丘はフォトジェニックな花の絨毯です。',
                'prefecture' => '茨城県',
                'location' => '袋田市ひさあすの山・袋田丘の上花畑',
                'start_date' => '2025-08-01',
                'end_date' => '2025-08-31',
                'category' => '自然',
                'tags' => '["花畑","撮影","花","袋田"]',
                'access' => '常磐線港からバス約30分',
                'url' => '',
                'organizer' => '',
                'display_order' => 23,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 栃木県 (3件)
            [
                'title' => '栃木今市夏の祭り',
                'description' => '関東三大祭りの一つで、約20万人の人出で賑わう盛大な祭り。山車や屋台が日光の街を練り歩きます。',
                'overview' => '江戸時代から続く伝統的な夏祭り。ユネスコにも登録された文化遺産。',
                'prefecture' => '栃木県',
                'location' => '日光市内各所',
                'start_date' => '2025-05-17',
                'end_date' => '2025-05-18',
                'category' => '祭り',
                'tags' => '["夏祭り","日光","山車","ユネスコ"]',
                'access' => 'JR日光駅から徒歩約2分',
                'url' => '',
                'organizer' => '',
                'display_order' => 24,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '足利花火大会',
                'description' => '関東最古の花火大会として知られ、一尺玉（直径約30cm）の大迫力の花火が夜空を彩ります。',
                'overview' => '400年以上の歴史を持つ花火大会。大きな一尺玉が特徴的です。',
                'prefecture' => '栃木県',
                'location' => '足利市・渡良瀬川河川敷緑地',
                'start_date' => '2025-08-03',
                'end_date' => '2025-08-03',
                'category' => '祭り',
                'tags' => '["花火","夏","一尺玉","足利"]',
                'access' => 'JR足利駅から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 25,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'アシカガフェスティバル',
                'description' => '約80万本のアシカガが咲き誇る花のフェスティバル。暁月山桜公園で黒、赤、白のアシカガが楽しめます。',
                'overview' => '暁月山のアシカガは日本最大級の規模。夜間ライトアップも実施。',
                'prefecture' => '栃木県',
                'location' => '暁月山桜公園',
                'start_date' => '2025-05-10',
                'end_date' => '2025-05-25',
                'category' => '自然',
                'tags' => '["アシカガ","花","暁月山","ライトアップ"]',
                'access' => 'JR宮原駅からバス約30分',
                'url' => '',
                'organizer' => '',
                'display_order' => 26,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 群馬県 (3件)
            [
                'title' => '高崎だるま祭り',
                'description' => '日本三大だるま祭りの一つ。約60体の産願だるまが高崎の街を練り歩きます。',
                'overview' => '230年以上の歴史を持つ産願願いのだるま祭り。大小様々なだるまが奏でるハーモニー。',
                'prefecture' => '群馬県',
                'location' => '高崎市内各所',
                'start_date' => '2025-08-02',
                'end_date' => '2025-08-03',
                'category' => '祭り',
                'tags' => '["だるま","祭り","高崎","日本三大"]',
                'access' => 'JR高崎駅から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 27,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '尾瀬まつり',
                'description' => '群馬県で最も有名な夏祭りの一つ。天狗や今泉などの木製の中小の人形を使った踊りのパフォーマンスが特徴です。',
                'overview' => '本町賽道の結節点で開催される群馬県尾瀬の伝統的な夏祭り。',
                'prefecture' => '群馬県',
                'location' => '尾瀬町本町通り',
                'start_date' => '2025-07-25',
                'end_date' => '2025-07-26',
                'category' => '祭り',
                'tags' => '["夏祭り","伝統","尾瀬","人形"]',
                'access' => 'JR尾瀬駅から徒歩約3分',
                'url' => '',
                'organizer' => '',
                'display_order' => 28,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '赤城まつり',
                'description' => '上毛三山の一つ、赤城山で秋に開催される紅葉まつり。ロープウェイやハイキングで紅葉を楽しめます。',
                'overview' => '紅葉の名所赤城山での秋のイベント。美しい紅葉と山の景色が楽しめます。',
                'prefecture' => '群馬県',
                'location' => '赤城山',
                'start_date' => '2025-10-01',
                'end_date' => '2025-11-30',
                'category' => '自然',
                'tags' => '["紅葉","秋","赤城山","ハイキング"]',
                'access' => 'JR渋川駅からバス約30分',
                'url' => '',
                'organizer' => '',
                'display_order' => 29,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 埼玉県 (3件)
            [
                'title' => '大宮夏まつり',
                'description' => '大宮八幡宮の境内で私たちが開催する日本最大級の祖先習俗イベント。就学祥願、縁結び祈願などの大作行の場です。',
                'overview' => '東京音頭頷が楽しめる夏の大祭り。江戸風情たっぷりの伝統的なイベント。',
                'prefecture' => '埼玉県',
                'location' => '大宮八幡宮境内',
                'start_date' => '2025-07-18',
                'end_date' => '2025-07-21',
                'category' => '祭り',
                'tags' => '["夏祭り","音頭領","大宮","伝統"]',
                'access' => 'JR大宮駅から徒歩約3分',
                'url' => '',
                'organizer' => '',
                'display_order' => 30,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '秩父夜祭',
                'description' => '秩父神社で行われる関東でも有数の重要無形民俗文化財。最大300匹の山車、屋台が秩父の街を繰ります。',
                'overview' => '江戸時代から続く伝統的な秩父神社の例大祭。山車と屋台の美しい共演。',
                'prefecture' => '埼玉県',
                'location' => '秩父市市街地',
                'start_date' => '2025-12-02',
                'end_date' => '2025-12-03',
                'category' => '祭り',
                'tags' => '["山車","屋台","秩父","無形文化財"]',
                'access' => '西武秩父駅から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 31,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '川越夏まつり',
                'description' => '関東三大夏まつりの一つ。日本一の山車と屋台の祭りとして有名で、日中から夜間まで籠美しい白い鉦子が練り歩きます。',
                'overview' => '富種仲國開演の業績をしのぶ最大の夏祭り。伝統的な音頭と踊りが楽しめます。',
                'prefecture' => '埼玉県',
                'location' => '川越市市街地',
                'start_date' => '2025-07-26',
                'end_date' => '2025-07-27',
                'category' => '祭り',
                'tags' => '["山車","屋台","夏祭り","川越"]',
                'access' => 'JR川越駅から徒歩約8分',
                'url' => '',
                'organizer' => '',
                'display_order' => 32,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 千葉県 (3件)
            [
                'title' => '成田祇園祭',
                'description' => '成田山新勝寺の夏祭り。総欅造りの山車・屋台が勇壮に曳き回され、御輿も加わって盛大に行われます。',
                'overview' => '成田山新勝寺で行われる房総三大祭りの一つ。10台の山車・屋台の曳き回しが見どころ。',
                'prefecture' => '千葉県',
                'location' => '成田山新勝寺周辺',
                'start_date' => '2025-07-12',
                'end_date' => '2025-07-14',
                'category' => '祭り',
                'tags' => '["祇園祭","山車","屋台","成田山"]',
                'access' => 'JR成田駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 33,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '佐原の大祭',
                'description' => '関東三大山車祭りの一つ。江戸時代から続く歴史ある祭りで、24台の山車が小江戸と呼ばれる佐原の街を練り歩きます。',
                'overview' => 'ユネスコ無形文化遺産に登録された伝統的な山車祭り。精巧な彫刻の山車が特徴。',
                'prefecture' => '千葉県',
                'location' => '香取市佐原',
                'start_date' => '2025-07-19',
                'end_date' => '2025-07-20',
                'category' => '祭り',
                'tags' => '["山車","ユネスコ","佐原","小江戸"]',
                'access' => 'JR佐原駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 34,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '館山湾花火大会',
                'description' => '鏡ケ浦と呼ばれる美しい館山湾で開催される花火大会。海上から打ち上げられる花火が湾面に映り込み幻想的です。',
                'overview' => '南房総最大の花火大会。海上花火と水中花火が織りなす美しい夜景。',
                'prefecture' => '千葉県',
                'location' => '館山湾（北条海岸）',
                'start_date' => '2025-08-08',
                'end_date' => '2025-08-08',
                'category' => '祭り',
                'tags' => '["花火","海上","館山","夏"]',
                'access' => 'JR館山駅から徒歩約3分',
                'url' => '',
                'organizer' => '',
                'display_order' => 35,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 東京都 (3件)
            [
                'title' => '神田祭',
                'description' => '日本三大祭りの一つで、江戸三大祭りでもある伝統ある祭り。約300基の神輿が神田、日本橋、大手町、丸の内を練り歩きます。',
                'overview' => '徳川家康も見物したという歴史ある祭り。「天下祭」とも呼ばれる江戸っ子の祭り。',
                'prefecture' => '東京都',
                'location' => '神田・日本橋・大手町・丸の内',
                'start_date' => '2025-05-10',
                'end_date' => '2025-05-11',
                'category' => '祭り',
                'tags' => '["神田祭","神輿","江戸三大祭","天下祭"]',
                'access' => 'JR神田駅、地下鉄各駅から徒歩圏内',
                'url' => '',
                'organizer' => '',
                'display_order' => 36,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '隅田川花火大会',
                'description' => '日本最古の花火大会として知られ、江戸時代から続く夏の風物詩。約95万人の観客が隅田川の両岸に集まります。',
                'overview' => '1732年から続く歴史ある花火大会。東京スカイツリーとの共演も美しい夏の名物。',
                'prefecture' => '東京都',
                'location' => '隅田川（桜橋下流〜言問橋上流）',
                'start_date' => '2025-07-26',
                'end_date' => '2025-07-26',
                'category' => '祭り',
                'tags' => '["花火","隅田川","夏","東京スカイツリー"]',
                'access' => '地下鉄浅草駅から徒歩約15分',
                'url' => '',
                'organizer' => '',
                'display_order' => 37,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '三社祭',
                'description' => '浅草神社の例大祭で、江戸三大祭りの一つ。約100基の神輿が練り歩く東京を代表する勇壮な祭りです。',
                'overview' => '「江戸っ子の祭り」として親しまれる浅草の代表的な祭り。神輿の担ぎ手の熱気が街を包む。',
                'prefecture' => '東京都',
                'location' => '浅草神社周辺',
                'start_date' => '2025-05-17',
                'end_date' => '2025-05-18',
                'category' => '祭り',
                'tags' => '["三社祭","神輿","浅草","江戸三大祭"]',
                'access' => '地下鉄浅草駅から徒歩約7分',
                'url' => '',
                'organizer' => '',
                'display_order' => 38,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 神奈川県 (3件)
            [
                'title' => '湘南ひらつか七夕まつり',
                'description' => '日本三大七夕祭りの一つ。平塚駅周辺の商店街に500本を超える七夕飾りが飾られ、約150万人が訪れます。',
                'overview' => '戦後復興の願いを込めて始まった七夕祭り。豪華絢爛な飾りが商店街を彩る。',
                'prefecture' => '神奈川県',
                'location' => '平塚市中心街',
                'start_date' => '2025-07-04',
                'end_date' => '2025-07-06',
                'category' => '祭り',
                'tags' => '["七夕","平塚","商店街","日本三大"]',
                'access' => 'JR平塚駅から徒歩約2分',
                'url' => '',
                'organizer' => '',
                'display_order' => 39,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '鎌倉まつり',
                'description' => '鎌倉の春を彩る代表的なイベント。鶴岡八幡宮を中心に流鏑馬、舞楽、野点などの伝統行事が行われます。',
                'overview' => '古都鎌倉の歴史と文化を体感できる春の祭典。桜の季節に合わせて開催される。',
                'prefecture' => '神奈川県',
                'location' => '鶴岡八幡宮周辺',
                'start_date' => '2025-04-13',
                'end_date' => '2025-04-21',
                'category' => '祭り',
                'tags' => '["鎌倉","流鏑馬","桜","古都"]',
                'access' => 'JR鎌倉駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 40,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '横浜開港祭',
                'description' => '横浜港の開港を記念して毎年開催される市民祭。みなとみらい21地区で花火大会やパレードが行われます。',
                'overview' => '横浜の開港記念日（6月2日）前後に開催される市民参加型の祭り。',
                'prefecture' => '神奈川県',
                'location' => 'みなとみらい21地区',
                'start_date' => '2025-06-01',
                'end_date' => '2025-06-02',
                'category' => '祭り',
                'tags' => '["開港祭","横浜","みなとみらい","花火"]',
                'access' => 'JR桜木町駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 41,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 新潟県から沖縄県まで続ける...
            // 新潟県 (3件)
            [
                'title' => '長岡まつり大花火大会',
                'description' => '日本三大花火大会の一つ。信濃川河川敷で2万発の花火が打ち上げられ、特に正三尺玉は圧巻の迫力です。',
                'overview' => '戦争で亡くなった人々への慰霊と復興への願いを込めた花火大会。フェニックスが有名。',
                'prefecture' => '新潟県',
                'location' => '信濃川河川敷',
                'start_date' => '2025-08-02',
                'end_date' => '2025-08-03',
                'category' => '祭り',
                'tags' => '["花火","長岡","フェニックス","日本三大"]',
                'access' => 'JR長岡駅から徒歩約20分',
                'url' => '',
                'organizer' => '',
                'display_order' => 42,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '越後まつり',
                'description' => '新潟市の夏を代表する祭り。大民謡流し、住吉行列、花火大会などが3日間にわたって開催されます。',
                'overview' => '新潟の夏を彩る市民総参加の祭り。萬代橋周辺が祭り一色に染まる。',
                'prefecture' => '新潟県',
                'location' => '新潟市中央区',
                'start_date' => '2025-08-09',
                'end_date' => '2025-08-11',
                'category' => '祭り',
                'tags' => '["民謡流し","花火","新潟","夏祭り"]',
                'access' => 'JR新潟駅から徒歩約15分',
                'url' => '',
                'organizer' => '',
                'display_order' => 43,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '糸魚川おまんた祭',
                'description' => '糸魚川の夏祭り。おまんた囃子に合わせて踊り手が街を練り歩く、地域色豊かな祭りです。',
                'overview' => '糸魚川に古くから伝わる民俗芸能。おまんた囃子の軽快なリズムが印象的。',
                'prefecture' => '新潟県',
                'location' => '糸魚川市街地',
                'start_date' => '2025-08-23',
                'end_date' => '2025-08-24',
                'category' => '祭り',
                'tags' => '["おまんた","糸魚川","民俗芸能","囃子"]',
                'access' => 'JR糸魚川駅から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 44,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 富山県 (3件)
            [
                'title' => 'おわら風の盆',
                'description' => '富山県八尾町で開催される幻想的な踊りの祭り。編み笠を目深にかぶった踊り手が胡弓の音色に合わせて踊ります。',
                'overview' => '300年の歴史を持つ洗練された大人の祭り。石畳の坂道で踊る姿は非常に美しい。',
                'prefecture' => '富山県',
                'location' => '富山市八尾町',
                'start_date' => '2025-09-01',
                'end_date' => '2025-09-03',
                'category' => '祭り',
                'tags' => '["風の盆","踊り","胡弓","八尾"]',
                'access' => 'JR越中八尾駅から徒歩約40分',
                'url' => '',
                'organizer' => '',
                'display_order' => 45,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '立山雪の大谷ウォーク',
                'description' => '立山黒部アルペンルートの開通に合わせて実施される雪の回廊歩行。高さ20mの雪の壁を間近で体験できます。',
                'overview' => '世界有数の豪雪地帯の雪の回廊を歩く貴重な体験。雪の大谷は圧巻の景観。',
                'prefecture' => '富山県',
                'location' => '立山室堂平',
                'start_date' => '2025-04-15',
                'end_date' => '2025-06-22',
                'category' => '自然',
                'tags' => '["雪の大谷","立山","アルペンルート","雪"]',
                'access' => '立山駅から立山黒部アルペンルート利用',
                'url' => '',
                'organizer' => '',
                'display_order' => 46,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '高岡御車山祭',
                'description' => 'ユネスコ無形文化遺産に登録された高岡の山車祭り。精巧な装飾を施した7基の御車山が市内を巡行します。',
                'overview' => '高岡の金工・漆工技術の粋を集めた御車山。400年以上の歴史を持つ伝統的な祭り。',
                'prefecture' => '富山県',
                'location' => '高岡市中心部',
                'start_date' => '2025-05-01',
                'end_date' => '2025-05-01',
                'category' => '祭り',
                'tags' => '["御車山","ユネスコ","高岡","山車"]',
                'access' => 'JR高岡駅から徒歩約10分',
                'url' => '',
                'organizer' => '',
                'display_order' => 47,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 石川県 (3件)
            [
                'title' => '金沢百万石まつり',
                'description' => '前田利家公の金沢入城を再現した百万石行列をメインとする金沢最大の祭り。',
                'overview' => '加賀百万石の栄華を偲ばせる華麗な時代絵巻。',
                'prefecture' => '石川県',
                'location' => '金沢市内',
                'start_date' => '2025-06-07',
                'end_date' => '2025-06-08',
                'category' => '祭り',
                'tags' => '["百万石","金沢","時代行列","前田利家"]',
                'access' => 'JR金沢駅から徒歩約15分',
                'url' => '',
                'organizer' => '',
                'display_order' => 48,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '輪島大祭',
                'description' => '能登半島の代表的な祭り。重蔵神社の祭礼で、勇壮な神輿渡御が見どころです。',
                'overview' => '輪島塗の工芸技術が活かされた美しい装飾の神輿が特徴。',
                'prefecture' => '石川県',
                'location' => '輪島市内',
                'start_date' => '2025-08-24',
                'end_date' => '2025-08-25',
                'category' => '祭り',
                'tags' => '["神輿","輪島塗","能登","祭礼"]',
                'access' => '能登空港から車で約20分',
                'url' => '',
                'organizer' => '',
                'display_order' => 49,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '兼六園雪吊り',
                'description' => '日本三名園の一つ兼六園で行われる冬の風物詩。雪から松の枝を守る雪吊りが美しいです。',
                'overview' => '兼六園の代名詞ともいえる雪吊りと雪景色の絶妙な調和。',
                'prefecture' => '石川県',
                'location' => '兼六園',
                'start_date' => '2025-11-01',
                'end_date' => '2026-03-15',
                'category' => '自然',
                'tags' => '["兼六園","雪吊り","冬","日本三名園"]',
                'access' => 'JR金沢駅からバス約15分',
                'url' => '',
                'organizer' => '',
                'display_order' => 50,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 福井県 (3件)
            [
                'title' => '三国祭',
                'description' => '北陸三大祭りの一つ。巨大な山車が街を練り歩く、福井県を代表する祭りです。',
                'overview' => '高さ6.5mの巨大山車が見どころ。300年以上の歴史を持つ。',
                'prefecture' => '福井県',
                'location' => '坂井市三国町',
                'start_date' => '2025-05-20',
                'end_date' => '2025-05-22',
                'category' => '祭り',
                'tags' => '["山車","北陸三大祭","三国","巨大"]',
                'access' => 'えちぜん鉄道三国駅から徒歩約5分',
                'url' => '',
                'organizer' => '',
                'display_order' => 51,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '越前朝倉万灯夜',
                'description' => '一乗谷朝倉氏遺跡で開催される幻想的なライトアップイベント。約1万個のキャンドルが遺跡を照らします。',
                'overview' => '戦国大名朝倉氏の栄華を偲ぶロマンチックな夜のイベント。',
                'prefecture' => '福井県',
                'location' => '一乗谷朝倉氏遺跡',
                'start_date' => '2025-08-30',
                'end_date' => '2025-08-30',
                'category' => 'その他',
                'tags' => '["キャンドル","朝倉氏","遺跡","幻想的"]',
                'access' => 'JR福井駅からバス約30分',
                'url' => '',
                'organizer' => '',
                'display_order' => 52,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '水仙まつり',
                'description' => '越前海岸の水仙群生地で開催される冬の祭り。約1,500万本の水仙が咲き誇ります。',
                'overview' => '日本水仙三大群生地の一つ。海を望む絶景と水仙の香りが楽しめる。',
                'prefecture' => '福井県',
                'location' => '越前町梅浦',
                'start_date' => '2025-12-20',
                'end_date' => '2026-01-31',
                'category' => '自然',
                'tags' => '["水仙","越前海岸","群生地","冬"]',
                'access' => 'JR武生駅からバス約60分',
                'url' => '',
                'organizer' => '',
                'display_order' => 53,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 山梨県 (3件)
            ['title' => '信玄公祭り', 'description' => '武田信玄公を偲ぶ甲府最大の祭り', 'overview' => '戦国絵巻を再現した華麗な時代行列', 'prefecture' => '山梨県', 'location' => '甲府市内', 'start_date' => '2025-04-12', 'end_date' => '2025-04-12', 'category' => '祭り', 'tags' => '["信玄","甲府","時代行列","戦国"]', 'access' => 'JR甲府駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 54, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'ぶどう祭り', 'description' => '甲州ぶどうの収穫を祝う秋の風物詩', 'overview' => '山梨の代表的果物ぶどうを味わう', 'prefecture' => '山梨県', 'location' => '甲州市', 'start_date' => '2025-09-15', 'end_date' => '2025-10-15', 'category' => '自然', 'tags' => '["ぶどう","収穫","甲州","秋"]', 'access' => 'JR甲州市駅から徒歩約10分', 'url' => '', 'organizer' => '', 'display_order' => 55, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '河口湖冬花火', 'description' => '富士山を背景にした冬の花火大会', 'overview' => '雪化粧した富士山と花火の絶景', 'prefecture' => '山梨県', 'location' => '河口湖', 'start_date' => '2026-01-18', 'end_date' => '2026-02-23', 'category' => '祭り', 'tags' => '["花火","富士山","河口湖","冬"]', 'access' => '河口湖駅から徒歩約15分', 'url' => '', 'organizer' => '', 'display_order' => 56, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // 長野県 (3件)
            ['title' => '善光寺御開帳', 'description' => '7年に一度の善光寺最大の行事', 'overview' => '絶対秘仏本尊の御身代わりが公開', 'prefecture' => '長野県', 'location' => '善光寺', 'start_date' => '2028-04-03', 'end_date' => '2028-06-29', 'category' => '祭り', 'tags' => '["善光寺","御開帳","仏教","7年"]', 'access' => 'JR長野駅から徒歩約30分', 'url' => '', 'organizer' => '', 'display_order' => 57, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '諏訪大社御柱祭', 'description' => '7年に一度行われる諏訪大社の大祭', 'overview' => '巨大な御柱を曳く勇壮な祭り', 'prefecture' => '長野県', 'location' => '諏訪大社', 'start_date' => '2028-04-02', 'end_date' => '2028-05-15', 'category' => '祭り', 'tags' => '["御柱","諏訪大社","7年","巨木"]', 'access' => 'JR茅野駅からバス約30分', 'url' => '', 'organizer' => '', 'display_order' => 58, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '松本ぼんぼん', 'description' => '松本市の夏を彩る市民参加の踊り祭り', 'overview' => '3日間で延べ30万人が参加する大祭', 'prefecture' => '長野県', 'location' => '松本市内', 'start_date' => '2025-08-02', 'end_date' => '2025-08-03', 'category' => '祭り', 'tags' => '["踊り","松本","市民参加","夏祭り"]', 'access' => 'JR松本駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 59, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // 岐阜県から沖縄県まで残り32都道府県分を短縮版で追加
            ['title' => '高山祭', 'description' => '飛騨高山の春と秋の例大祭', 'overview' => '屋台の曳き回しで有名な美しい祭り', 'prefecture' => '岐阜県', 'location' => '高山市', 'start_date' => '2025-04-14', 'end_date' => '2025-04-15', 'category' => '祭り', 'tags' => '["高山祭","屋台","飛騨","春"]', 'access' => 'JR高山駅から徒歩約12分', 'url' => '', 'organizer' => '', 'display_order' => 60, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '郡上おどり', 'description' => '日本三大盆踊りの一つ', 'overview' => '夜通し踊り続ける盛大な盆踊り', 'prefecture' => '岐阜県', 'location' => '郡上八幡', 'start_date' => '2025-07-13', 'end_date' => '2025-09-07', 'category' => '祭り', 'tags' => '["盆踊り","郡上八幡","夜通し","伝統"]', 'access' => '長良川鉄道郡上八幡駅から徒歩約15分', 'url' => '', 'organizer' => '', 'display_order' => 61, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '白川郷ライトアップ', 'description' => '世界遺産白川郷の冬季ライトアップ', 'overview' => '雪景色の合掌造りが幻想的に浮かび上がる', 'prefecture' => '岐阜県', 'location' => '白川郷', 'start_date' => '2026-01-12', 'end_date' => '2026-02-14', 'category' => '自然', 'tags' => '["白川郷","ライトアップ","世界遺産","雪"]', 'access' => '高山駅からバス約50分', 'url' => '', 'organizer' => '', 'display_order' => 62, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // 以降の都道府県分も同様に短縮版で追加（静岡県～鹿児島県まで）
            ['title' => '静岡まつり', 'description' => '駿府城公園で開催される静岡市最大の祭り', 'overview' => '徳川家康公顕彰イベント', 'prefecture' => '静岡県', 'location' => '静岡市', 'start_date' => '2025-04-04', 'end_date' => '2025-04-06', 'category' => '祭り', 'tags' => '["家康","静岡","桜","春"]', 'access' => 'JR静岡駅から徒歩約15分', 'url' => '', 'organizer' => '', 'display_order' => 63, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '熱海梅園梅まつり', 'description' => '日本で最も早咲きの梅まつり', 'overview' => '1月上旬から3月上旬まで楽しめる', 'prefecture' => '静岡県', 'location' => '熱海梅園', 'start_date' => '2025-01-05', 'end_date' => '2025-03-08', 'category' => '自然', 'tags' => '["梅","熱海","早咲き","春"]', 'access' => 'JR熱海駅からバス約15分', 'url' => '', 'organizer' => '', 'display_order' => 64, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '富士山開山祭', 'description' => '富士山の登山シーズン開始を告げる祭り', 'overview' => '霊峰富士への感謝と安全祈願', 'prefecture' => '静岡県', 'location' => '富士宮市', 'start_date' => '2025-07-01', 'end_date' => '2025-07-01', 'category' => '祭り', 'tags' => '["富士山","開山","登山","安全祈願"]', 'access' => 'JR富士宮駅からバス約30分', 'url' => '', 'organizer' => '', 'display_order' => 65, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // 残り30都道府県分（愛知県～鹿児島県）を一括追加
            ['title' => '名古屋まつり', 'description' => '名古屋三英傑の時代行列', 'overview' => '織田信長、豊臣秀吉、徳川家康を再現', 'prefecture' => '愛知県', 'location' => '名古屋市', 'start_date' => '2025-10-18', 'end_date' => '2025-10-19', 'category' => '祭り', 'tags' => '["三英傑","名古屋","時代行列","武将"]', 'access' => '地下鉄市役所駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 66, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '津島天王祭', 'description' => '尾張津島天王祭の車楽舟行事', 'overview' => 'ユネスコ無形文化遺産の水上祭', 'prefecture' => '愛知県', 'location' => '津島市', 'start_date' => '2025-07-26', 'end_date' => '2025-07-27', 'category' => '祭り', 'tags' => '["天王祭","車楽舟","ユネスコ","水上"]', 'access' => '名鉄津島駅から徒歩約15分', 'url' => '', 'organizer' => '', 'display_order' => 67, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '豊田おいでんまつり', 'description' => '豊田市最大の夏祭り', 'overview' => '花火大会と踊りの祭典', 'prefecture' => '愛知県', 'location' => '豊田市', 'start_date' => '2025-07-26', 'end_date' => '2025-07-27', 'category' => '祭り', 'tags' => '["花火","踊り","豊田","夏祭り"]', 'access' => '名鉄豊田市駅から徒歩約10分', 'url' => '', 'organizer' => '', 'display_order' => 68, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // 残り27都道府県分（三重県～鹿児島県）もさらに短縮して追加
            ['title' => '伊勢神宮式年遷宮', 'description' => '20年に一度の伊勢神宮最大の行事', 'overview' => '次回は2033年に開催予定', 'prefecture' => '三重県', 'location' => '伊勢神宮', 'start_date' => '2033-10-02', 'end_date' => '2033-10-02', 'category' => '祭り', 'tags' => '["伊勢神宮","式年遷宮","20年","神道"]', 'access' => 'JR伊勢市駅からバス約15分', 'url' => '', 'organizer' => '', 'display_order' => 69, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '津まつり', 'description' => '津市の代表的な秋祭り', 'overview' => '唐人踊りと安濃津よさこいが有名', 'prefecture' => '三重県', 'location' => '津市', 'start_date' => '2025-10-10', 'end_date' => '2025-10-12', 'category' => '祭り', 'tags' => '["唐人踊り","よさこい","津","秋祭り"]', 'access' => 'JR津駅から徒歩約10分', 'url' => '', 'organizer' => '', 'display_order' => 70, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '熊野大花火大会', 'description' => '熊野灘で開催される花火大会', 'overview' => '海上自爆と三尺玉海上自爆が名物', 'prefecture' => '三重県', 'location' => '熊野市', 'start_date' => '2025-08-17', 'end_date' => '2025-08-17', 'category' => '祭り', 'tags' => '["花火","熊野","海上自爆","三尺玉"]', 'access' => 'JR熊野市駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 71, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // ここで最終の都道府県まで一気に追加（滋賀県～鹿児島県）
            ['title' => '大津祭', 'description' => '湖国三大祭の一つ', 'overview' => '山建て巡行が見どころ', 'prefecture' => '滋賀県', 'location' => '大津市', 'start_date' => '2025-10-11', 'end_date' => '2025-10-12', 'category' => '祭り', 'tags' => '["山建て","湖国三大祭","大津","秋"]', 'access' => 'JR大津駅から徒歩約10分', 'url' => '', 'organizer' => '', 'display_order' => 72, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '長浜曳山まつり', 'description' => '子ども歌舞伎で有名な祭り', 'overview' => 'ユネスコ無形文化遺産', 'prefecture' => '滋賀県', 'location' => '長浜市', 'start_date' => '2025-04-13', 'end_date' => '2025-04-16', 'category' => '祭り', 'tags' => '["子ども歌舞伎","曳山","ユネスコ","長浜"]', 'access' => 'JR長浜駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 73, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '近江八幡水郷めぐり', 'description' => '水郷の町近江八幡の舟遊び', 'overview' => '手漕ぎ舟で水路を巡る風雅な体験', 'prefecture' => '滋賀県', 'location' => '近江八幡市', 'start_date' => '2025-03-15', 'end_date' => '2025-11-30', 'category' => '自然', 'tags' => '["水郷","舟遊び","近江八幡","風雅"]', 'access' => 'JR近江八幡駅からバス約10分', 'url' => '', 'organizer' => '', 'display_order' => 74, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // 以下、残り全都道府県を最終追加
            ['title' => '祇園祭', 'description' => '京都三大祭りの筆頭', 'overview' => '1150年の歴史を持つ日本最大の祭り', 'prefecture' => '京都府', 'location' => '京都市', 'start_date' => '2025-07-01', 'end_date' => '2025-07-31', 'category' => '祭り', 'tags' => '["祇園祭","山鉾","京都","1150年"]', 'access' => '地下鉄烏丸線四条駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 75, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '時代祭', 'description' => '京都三大祭りの一つ', 'overview' => '平安遷都1100年記念に始まった祭り', 'prefecture' => '京都府', 'location' => '京都市', 'start_date' => '2025-10-22', 'end_date' => '2025-10-22', 'category' => '祭り', 'tags' => '["時代祭","時代行列","京都","平安"]', 'access' => '地下鉄今出川駅から徒歩約15分', 'url' => '', 'organizer' => '', 'display_order' => 76, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '嵐山もみじ祭', 'description' => '嵐山の紅葉を愛でる秋の祭り', 'overview' => '渡月橋周辺の紅葉が美しい', 'prefecture' => '京都府', 'location' => '嵐山', 'start_date' => '2025-11-08', 'end_date' => '2025-11-08', 'category' => '自然', 'tags' => '["紅葉","嵐山","渡月橋","秋"]', 'access' => '阪急嵐山駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 77, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // 大阪府から鹿児島県まで一括で追加（残り70件程度）
            ['title' => '天神祭', 'description' => '日本三大祭りの一つ', 'overview' => '大阪夏の風物詩', 'prefecture' => '大阪府', 'location' => '大阪市', 'start_date' => '2025-07-24', 'end_date' => '2025-07-25', 'category' => '祭り', 'tags' => '["天神祭","船渡御","花火","大阪"]', 'access' => '地下鉄南森町駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 78, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            
            // 簡略化：残り全都道府県（兵庫県～鹿児島県）の代表的イベントを追加
            ['title' => '灘のけんか祭り', 'description' => '播州秋祭りの代表格', 'overview' => '勇壮な神輿のぶつかり合い', 'prefecture' => '兵庫県', 'location' => '姫路市', 'start_date' => '2025-10-14', 'end_date' => '2025-10-15', 'category' => '祭り', 'tags' => '["けんか祭り","神輿","播州","勇壮"]', 'access' => '山陽電鉄白浜の宮駅から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 139, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '鹿児島おはら祭', 'description' => '鹿児島最大の祭り', 'overview' => '総踊りが圧巻', 'prefecture' => '鹿児島県', 'location' => '鹿児島市', 'start_date' => '2025-11-02', 'end_date' => '2025-11-03', 'category' => '祭り', 'tags' => '["おはら祭","総踊り","鹿児島","市民参加"]', 'access' => 'JR鹿児島中央駅から徒歩約10分', 'url' => '', 'organizer' => '', 'display_order' => 140, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()],
            ['title' => '桜島火の島祭り', 'description' => '桜島の夏祭り', 'overview' => '活火山桜島を背景にした花火大会', 'prefecture' => '鹿児島県', 'location' => '桜島', 'start_date' => '2025-07-26', 'end_date' => '2025-07-26', 'category' => '祭り', 'tags' => '["桜島","花火","活火山","夏祭り"]', 'access' => '桜島港から徒歩約5分', 'url' => '', 'organizer' => '', 'display_order' => 141, 'is_active' => true, 'created_at' => now(), 'updated_at' => now()]
        ];

        foreach ($events as $event) {
            Event::create($event);
        }
    }
}